FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Create a working directory for the app
WORKDIR /app

# Install system dependencies for Postgres
RUN apt-get update && apt-get install -y gcc libpq-dev

# Copy the requirements.txt file to the container
COPY requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire app to the container
COPY . /app/

# Expose the port that the app will run on
EXPOSE 5000

# Run the app
CMD ["flask", "run", "--host=0.0.0.0"]